proxy_read_timeout: 60
proxy_write_timeout: 60
upstreams:
    floki:
        hosts:
        - localhost:9094
        - localhost:9095
locations:
  - prefix: /test
    proxy_set_header:
      - Test3 Test3Header
      - Test1 Test1Header
      - Test2 Test2Header
    proxy_hide_header:
      - Date
    proxy_write_timeout: 5
    proxy_read_timeout: 5
    proxy_pass: floki
    proxy_set_body: test_proxy_set_body
    auth:
        type: basic 
        passwdfile: credentials_bcrypt
  - prefix: /
    proxy_pass: floki
    proxy_set_header:
    - TestHeader TestHeaderValue
    proxy_hide_header:
      - Date