version: '2'
services:
  backend:
    image: local/nginxlab
    entrypoint: nginx -g 'daemon off;' -c /etc/nginx/backend.conf
    hostname: backend
    ports:
    - 8082:8082
    cap_add:
    - NET_ADMIN
  headersdebugger:
    image: brndnmtthws/nginx-echo-headers
    ports:
    - 8083:8080
  