version: '2'
services:
  backend1:
    image: local/nginxlab
    entrypoint: nginx -g 'daemon off;' -c /etc/nginx/backend.conf
    hostname: backend1
    ports:
    - 9094:8082
    cap_add:
    - NET_ADMIN
  backend2:
    image: local/nginxlab
    entrypoint: nginx -g 'daemon off;' -c /etc/nginx/backend.conf
    hostname: backend2
    ports:
    - 9095:8082
    cap_add:
    - NET_ADMIN
#  headersdebugger:
#    image: brndnmtthws/nginx-echo-headers
#    ports:
#    - 8083:8080
  
